#!/usr/bin/env php
<?php

// set to run indefinitely if needed
set_time_limit(0);

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php';

// import the Symfony Console Application
use Symfony\Component\Console\Application;
use Wkse\Commands\ZipCommand;
use Wkse\Commands\ComposerCommand;
use Wkse\Commands\ScpCommand;

$app = new Application();
$app->addCommands(array(
  new ComposerCommand(),
  new ZipCommand(),
  new ScpCommand(),

));
$app->run();
?>
