#!/usr/bin/env php
<?php
// set to run indefinitely if needed
set_time_limit(0);
date_default_timezone_set('Europe/Stockholm');
// Ensure that errors are only reported once.
ini_set('display_errors', 1);
ini_set('log_errors', 0);
// Include the composer autoloader
define('CLI_ROOT', __DIR__);

if (file_exists(__DIR__ . '/../vendor/autoload.php')) {
  require __DIR__ . '/../vendor/autoload.php';
}

if (file_exists(CLI_ROOT . '/vendor/autoload.php')) {
  require CLI_ROOT . '/vendor/autoload.php';
}
elseif (file_exists(CLI_ROOT . '/../../../autoload.php')) {
  // we are globally installed via Composer
  require CLI_ROOT . '/../../../autoload.php';
}

use Symfony\Component\Console\Application;

use Dropcat\Command\BackupCommand;
use Dropcat\Command\ConfigImportCommand;
use Dropcat\Command\DbImportCommand;
use Dropcat\Command\DeployCommand;
use Dropcat\Command\UploadCommand;
use Dropcat\Command\SymlinkCommand;
use Dropcat\Command\TarCommand;
use Symfony\Component\Config\Loader\FileLoader;
use Symfony\Component\Yaml\Yaml;

$app = new Application();
$app->addCommands(array(
  new BackupCommand(),
  new ConfigImportCommand(),
  new DbImportCommand(),
  new DeployCommand(),
  new UploadCommand(),
  new SymlinkCommand(),
  new TarCommand(),
));
$app->run();
